//Ο menu

document.write("<div class='halfmoon'>");
document.write("<ul>");
document.write("<li><a href='x.html'><img src='image/back.png' alt='back' /></a> </li>");
document.write("<li><a href='o.html'>ο</a></li>");
document.write("<li><a href='ob.html'>οβ</a></li>");
document.write("<li><a href='og.html'>ογ</a></li>");
document.write("<li><a href='od.html'>οδ</a></li>");
document.write("<li><a href='oz.html'>οζ</a></li>");
document.write("<li><a href='oq.html'>οθ</a></li>");
document.write("<li><a href='oi.html'>οι</a></li>");
document.write("<li><a href='ok.html'>οκ</a></li>");
document.write("<li><a href='ol.html'>ολ</a></li>");
document.write("<li><a href='om.html'>ομ</a></li>");
document.write("<li><a href='on.html'>ον</a></li>");
document.write("</ul>");
document.write("</div>");
document.write("<div class='halfmoon'>");
document.write("<ul>");
document.write("<li><a href='ox.html'>οξ</a></li>");
document.write("<li><a href='oo.html'>οο</a></li>");
document.write("<li><a href='op.html'>οπ</a></li>");
document.write("<li><a href='or.html'>ορ</a></li>");
document.write("<li><a href='os.html'>οσ</a></li>");
document.write("<li><a href='ot.html'>οτ</a></li>");
document.write("<li><a href='ou.html'>ου</a></li>");
document.write("<li><a href='of.html'>οφ</a></li>");
document.write("<li><a href='oc.html'>οχ</a></li>");
document.write("<li><a href='oy.html'>οψ</a></li>");
document.write("<li><a href='p.html'><img src='image/forth.png' alt='forth' /></a> </li>");								
document.write("</ul>");
document.write("</div>");
