//<script src='../js/cognate/adelfos.js'></script>
document.write("<li><span class='cat'>Cognates: </span>");
document.write("<p class='box'>");
document.write("<a href='ade.html#adelfos'>ἀδελφός</a> =brother, ");
document.write("<a href='anad.html#anadelfos'>ἀνάδελφος</a>=without sibling, ");
document.write("<a href='and.html#andradelfos'>ἀνδράδελφος</a>=brother-in-law, ");
document.write("<a href='aut.html#autadelfos'>αὐτάδελφος</a>=belonging to sibling, ");
document.write("<a href='gu.html#gunaikadelfos'>γυναικάδελφος</a>=wife’s brother, ");
document.write("<a href='dis.html#disexadelfos'>δισεξάδελφος</a>=great-nephew, ");
document.write("<a href='du.html#dusadelfos'>δυσάδελφος</a>=unhappy brother, ");
document.write("<a href='exad.html#exadelfos'>ἐξάδελφος</a>=nephew, ");
document.write("<a href='is.html#isadelfos'>ἰσάδελφος</a>=like a brother, ");
document.write("<a href='li.html#lipadelfos'>λιπάδελφος</a>=brotherless, ");
document.write("<a href='mh.html#mhtradelfos'>μητράδελφος</a>=uncle, aunt, ");
document.write("<a href='mi.html#misadelfos'>μισάδελφος</a>=hating brother, ");
document.write("<a href='ol.html#oligadelfos'>ὀλιγάδελφος</a>=have few brothers, ");
document.write("<a href='pat.html#patradelfos'>πατράδελφος</a>=uncle, ");
document.write("<a href='peris.html#perissadelfos'>περισσάδελφος</a>=many brothers, ");
document.write("<a href='pol.html#poluadelfos'>πολυάδελφος</a>=many brothers, ");
document.write("<a href='sp.html#spanadelfos'>σπανάδελφος</a>=few siblings, ");
document.write("<a href='sunad.html#sunadelfos'>συνάδελφος</a>=having a sibling, ");
document.write("<a href='tri.html#triadelfos'>τριάδελφος</a>=3 brothers, ");
document.write("<a href='fi.html#filadelfos'>φιλάδελφος</a>=love sibling, ");
document.write("<a href='ye.html#yeudadelfos'>ψευδάδελφος</a>=false brother");
document.write("</p></li>");