document.write("<div class='halfmoon'>");
document.write("<ul>");
document.write(" <li><span class='w'>Chapter:</span> </li>");
document.write(" <li><a href='1clem01.html'>1</a></li>");
document.write(" <li><a href='1clem02.html'>2</a></li>");
document.write(" <li><a href='1clem03.html'>3</a></li>");
document.write(" <li><a href='1clem04.html'>4</a></li>");
document.write(" <li><a href='1clem05.html'>5</a></li>");
document.write(" <li><a href='1clem06.html'>6</a></li>");
document.write(" <li><a href='1clem07.html'>7</a></li>");
document.write(" <li><a href='1clem08.html'>8</a></li>");
document.write(" <li><a href='1clem09.html'>9</a></li>");
document.write(" <li><a href='1clem10.html'>10</a></li>");
document.write(" <li><a href='1clem11.html'>11</a></li>");

document.write(" <li><a href='1clem12.html'>12</a></li>");
document.write(" <li><a href='1clem13.html'>13</a></li>");
document.write(" <li><a href='1clem14.html'>14</a></li>");
document.write(" <li><a href='1clem15.html'>15</a></li>");
document.write(" <li><a href='1clem16.html'>16</a></li>");
document.write(" <li><a href='1clem17.html'>17</a></li>");
document.write(" <li><a href='1clem18.html'>18</a></li>");
document.write(" <li><a href='1clem19.html'>19</a></li>");
document.write(" <li><a href='1clem20.html'>20</a></li>");
document.write(" <li><a href='1clem21.html'>21</a></li>");

document.write(" <li><a href='1clem22.html'>22</a></li>");
document.write(" <li><a href='1clem23.html'>23</a></li>");
document.write(" <li><a href='1clem24.html'>24</a></li>");
document.write(" <li><a href='1clem25.html'>25</a></li>");
document.write(" <li><a href='1clem26.html'>26</a></li>");
document.write(" <li><a href='1clem27.html'>27</a></li>");
document.write(" <li><a href='1clem28.html'>28</a></li>");
document.write(" <li><a href='1clem29.html'>29</a></li>");
document.write(" <li><a href='1clem30.html'>30</a></li>");
document.write(" <li><a href='1clem31.html'>31</a></li>");

document.write(" <li><a href='1clem32.html'>32</a></li>");
document.write(" <li><a href='1clem33.html'>33</a></li>");
document.write(" <li><a href='1clem34.html'>34</a></li>");
document.write(" <li><a href='1clem35.html'>35</a></li>");
document.write(" <li><a href='1clem36.html'>36</a></li>");
document.write(" <li><a href='1clem37.html'>37</a></li>");
document.write(" <li><a href='1clem38.html'>38</a></li>");
document.write(" <li><a href='1clem39.html'>39</a></li>");
document.write(" <li><a href='1clem40.html'>40</a></li>");
document.write(" <li><a href='1clem41.html'>41</a></li>");

document.write(" <li><a href='1clem42.html'>42</a></li>");
document.write(" <li><a href='1clem43.html'>43</a></li>");
document.write(" <li><a href='1clem44.html'>44</a></li>");
document.write(" <li><a href='1clem45.html'>45</a></li>");
document.write(" <li><a href='1clem46.html'>46</a></li>");
document.write(" <li><a href='1clem47.html'>47</a></li>");
document.write(" <li><a href='1clem48.html'>48</a></li>");
document.write(" <li><a href='1clem49.html'>49</a></li>");
document.write(" <li><a href='1clem50.html'>50</a></li>");
document.write(" <li><a href='1clem51.html'>51</a></li>");

document.write(" <li><a href='1clem52.html'>52</a></li>");
document.write(" <li><a href='1clem53.html'>53</a></li>");
document.write(" <li><a href='1clem54.html'>54</a></li>");
document.write(" <li><a href='1clem55.html'>55</a></li>");
document.write(" <li><a href='1clem56.html'>56</a></li>");
document.write(" <li><a href='1clem57.html'>57</a></li>");
document.write(" <li><a href='1clem58.html'>58</a></li>");
document.write(" <li><a href='1clem59.html'>59</a></li>");
document.write(" <li><a href='1clem60.html'>60</a></li>");
document.write(" <li><a href='1clem61.html'>61</a></li>");

document.write(" <li><a href='1clem62.html'>62</a></li>");
document.write(" <li><a href='1clem63.html'>63</a></li>");
document.write(" <li><a href='1clem64.html'>64</a></li>");
document.write(" <li><a href='1clem65.html'>65</a></li>");
document.write(" <li><a href='2clem01.html'>II&nbsp;Clement</a></li>");
document.write("</ul>");
document.write("</div>");
