
document.write("<div class='halfmoon'>");
document.write("<ul>");
document.write(" <li><span class='w'>Chapter:</span> </li>");
document.write(" <li><a href='#chapter01'>1</a></li>");
document.write(" <li><a href='#chapter02'>2</a></li>");
document.write(" <li><a href='#chapter03'>3</a></li>");
document.write(" <li><a href='#chapter04'>4</a></li>");
document.write(" <li><a href='#chapter05'>5</a></li>");
document.write(" <li><a href='#chapter06'>6</a></li>");
document.write(" <li><a href='#chapter07'>7</a></li>");
document.write(" <li><a href='#chapter08'>8</a></li>");
document.write(" <li><a href='#chapter09'>9</a></li>");
document.write(" <li><a href='#chapter10'>10</a></li>");
document.write(" <li><a href='#chapter11'>11</a></li>");
//document.write("</br></br>");
document.write(" <li><a href='#chapter12'>12</a></li>");
document.write(" <li><a href='#chapter13'>13</a></li>");
document.write(" <li><a href='#chapter14'>14</a></li>");
document.write(" <li><a href='#chapter15'>15</a></li>");
document.write(" <li><a href='#chapter16'>16</a></li>");
document.write(" <li><a href='#chapter17'>17</a></li>");
document.write(" <li><a href='#chapter18'>18</a></li>");
document.write(" <li><a href='#chapter19'>19</a></li>");
document.write(" <li><a href='#chapter20'>20</a></li>");
document.write(" <li><a href='#chapter21'>21</a></li>");
document.write("</ul>");
document.write("</div>");
