document.write("<div class='navbar'>");
	document.write("<div class='dropdown'>");
		document.write("<button class='dropbtn'>Home ");
			document.write("<i class='fa fa-caret-down'></i>");
		document.write("</button>");
		document.write("<div class='dropdown-content'>");
			document.write("<a href='../index.html' title='Main Index'><img src='../images/home.gif' alt='home'></a>");
			document.write("<a href='../nt/mt01.html' title='New Testament'>NT (NAS)</a>");
			document.write("<a href='../nt-tr/mt01.html' title='New Testament'>NT (TexRec)</a>");
			
			document.write("<a href='../nt-poly/mt01.html' title='New Testament'>NT Polyglot</a>");
			
			document.write("<a href='../lxx/genesis01.html' title='Old Testament, Septuagint'>OT (LXX)</a>");
			document.write("<a href='../polyglot/genesis01.html' title='polyglot'>OT Polyglot</a>");

			document.write("<a href='../apocrypha/baruch1.html'>Apocrypha</a>");
			document.write("<a href='../lessons/lesson01.html' title='How to learn Greek'>Tutorial</a>");
			document.write("<a href='../lexicon/a.html' title='Analytic Greek dictionary'>Lexicon</a>");
			document.write("<a href='../english/intro.html' title='English to Greek'>English to Greek</a>");
document.write("<a href='../trivia/trivia.html' title='Greek trivia'>Trivia</a>");
			document.write("<a href='../literature/books.html' title='Available books for sale'>Literature</a>");
			document.write("<a href='../help/help.html'>Help</a>");
			document.write("<a href='../about/about.html' title='contact information'>About</a>");
		document.write("</div>");
	document.write("</div> ");
	document.write("<div class='dropdown'>");
		document.write("<button class='dropbtn'>Clement ");
			document.write("<i class='fa fa-caret-down'></i>");
		document.write("</button>");
		document.write("<div class='dropdown-content'>");
			document.write("<a href='1clem01.html'>1 Corinthians</a>");
			document.write("<a href='2clem01.html'>2 Corinthians</a>");
		document.write("</div>");
	document.write("</div> ");
	 document.write("<div class='dropdown'>");
		document.write("<button class='dropbtn'>Ignatius ");
		  document.write("<i class='fa fa-caret-down'></i>");
		document.write("</button>");
		document.write("<div class='dropdown-content'>");
			document.write("<a href='i-ephesians.html'>Ephesians</a>");
			document.write("<a href='i-magnesians.html'>Magnesians</a>");
			document.write("<a href='i-trallians.html'>Trallians</a>");
			document.write("<a href='i-romans.html'>Romans</a>");
			document.write("<a href='i-philadelphians.html'>Philadelphians</a>");
			document.write("<a href='i-smyrnaeans.html'>Smyrnaeans</a>");
			document.write("<a href='i-polycarp.html'>Polycarp</a>");
		document.write("</div>");
	  document.write("</div> ");
	 document.write("<div class='dropdown'>");
		document.write("<button class='dropbtn'>Hermas ");
		  document.write("<i class='fa fa-caret-down'></i>");
		document.write("</button>");
		document.write("<div class='dropdown-content'>");
			document.write("<a href='vision01.html'>Visions</a>");
			document.write("<a href='mandate01.html'>Mandates</a>");
			document.write("<a href='parable01.html'>Parables</a>");
		document.write("</div>");
	  document.write("</div> ");
		document.write("<div class='dropdown'>");
		document.write("<button class='dropbtn'>Papias ");
		  document.write("<i class='fa fa-caret-down'></i>");
		document.write("</button>");
		document.write("<div class='dropdown-content'>");
			document.write("<a href='papias.html'>Fragments</a>");
			document.write("<a href='papias-tr.html'>Tradition</a>");
		document.write("</div>");
		document.write("</div> ");
		document.write("<div class='dropdown'>");
		document.write("<button class='dropbtn'>Irenaeus ");
		  document.write("<i class='fa fa-caret-down'></i>");
		document.write("</button>");
		document.write("<div class='dropdown-content'>");
			document.write("<a href='irenaeus.html'>Martyrdom of Polycarp</a>");
		document.write("</div>");
		document.write("</div> ");

		document.write("<div class='dropdown'>");
		document.write("<button class='dropbtn'>Polycarp ");
		  document.write("<i class='fa fa-caret-down'></i>");
		document.write("</button>");
		document.write("<div class='dropdown-content'>");
			document.write("<a href='philippians.html'>Polycarp to Philippians</a>");
			document.write("<a href='i-polycarp.html'>Irenaeus to Polycarp</a>");
			document.write("<a href='irenaeus.html'>Martyrdom of Polycarp</a>");

		document.write("</div>");

		document.write("</div> ");
		document.write("<div class='dropdown'>");
		document.write("<button class='dropbtn'>Others ");
		  document.write("<i class='fa fa-caret-down'></i>");
		document.write("</button>");
		document.write("<div class='dropdown-content'>");
			document.write("<a href='barnabas.html'>Barnabas</a>");
			document.write("<a href='didache.html'>Didache</a>");
			document.write("<a href='diognetus.html'>Diognetus</a>");
			document.write("<a href='quadratus.html'>Quadratus</a>");
		document.write("</div>");
	document.write("</div> ");
document.write("</div>");
