document.write("<div class='halfmoon'>");
document.write("<ul>");
document.write(" <li><span class='w'>Mandate:</span> </li>");
document.write(" <li><a href='mandate01.html'>1</a></li>");
document.write(" <li><a href='mandate02.html'>2</a></li>");
document.write(" <li><a href='mandate03.html'>3</a></li>");
document.write(" <li><a href='mandate04.html'>4</a></li>");
document.write(" <li><a href='mandate05.html'>5</a></li>");
document.write(" <li><a href='mandate06.html'>6</a></li>");
document.write(" <li><a href='mandate07.html'>7</a></li>");
document.write(" <li><a href='mandate08.html'>8</a></li>");
document.write(" <li><a href='mandate09.html'>9</a></li>");
document.write(" <li><a href='mandate10.html'>10</a></li>");
document.write(" <li><a href='mandate11.html'>11</a></li>");
//document.write("</br></br>");
document.write(" <li><a href='mandate12.html'>12</a></li>");
//document.write("</br></br>");
			document.write(" <li><a href='parable01.html'>Parables</a></li>");
			document.write(" <li><a href='vision01.html'>Visions</a></li>");
document.write("</ul>");
document.write("</div>");
