//list of conjunctions
//<script src='js/conjunction.js'></script>



document.write("<p class='box'><span class='b'>LIST OF CONJUNCTIONS<br />");

document.write("<a href='all.html#alla'>ἀλλά</a>, ");
document.write("<a href='ara.html#ara'>ἄρα</a>, ");
document.write("<a href='at.html#atar'>ἀτάρ</a>, ");
document.write("<a href='ac.html#acri'>άχρί</a>, ");
document.write("<a href='ga.html#gar'>γάρ</a>, ");
document.write("<a href='de.html#de'>δέ</a>, ");
document.write("<a href='diat.html#diatouto'>διατοῦτο</a>, ");
document.write("<a href='dio.html#dio'>διό</a>, ");
document.write("<a href='dio.html#dioper'>διόπερ</a>, ");
document.write("<a href='dio.html#dioti'>διότι</a>, ");
document.write("<a href='ea.html#ean'>ἐάν</a>, ");
document.write("<a href='ea.html#eanper'>ἐάνπερ</a>, ");
document.write("<a href='ei.html#ei'>εἰ</a>, ");
document.write("<a href='ei.html#eidemhge'>(εἰ δὲ μήγε)</a>, ");
document.write("<a href='ei.html#eige'>(εἴ γε)</a>, ");
document.write("<a href='eia.html#ei ara'>(εἰ ἄρα)</a>, ");
document.write("<a href='eid.html#eidekai'>(εἰ δὲ καὶ)</a>, ");
document.write("<a href='eid.html#eidemh'>(εἰ δὲ μή)</a>, ");
document.write("<a href='eid.html#eidemhge'>(εἰ δὲ μή γε), (εἰ δὲ μήγε)</a>, ");
document.write("<a href='eig.html#eige'>(εἴ γε), εἴγε</a>, ");
document.write("<a href='eik.html#eikai'>(εἰ καί)</a>, ");
document.write("<a href='eim.html#eimengar'>(εἰ μὲν γαρ)</a>, ");
document.write("<a href='eim.html#eimenoun'>(εἰ μὲν οὖν)</a>, ");
document.write("<a href='eim.html#eimhoti'>(εἰ μὴ ὅτι)</a>, ");
document.write("<a href='eim.html#eimhti'>(εἰ μήτι), (εἰ μή τι)</a>, ");
document.write("<a href='eio.html#eioun'>(εἰ οὖν)</a>, ");
document.write("<a href='eip.html#eiper'>εἴπερ</a>, ");
document.write("<a href='eip.html#eipws'>εἴπως, (εἴ πως)</a>, ");
document.write("<a href='eis.html#eis7'>εἴς</a>, ");
document.write("<a href='eit.html#eite'>εἴτε</a>, ");
document.write("<a href='eit.html#ei)~te'>εἶτε</a>, ");
document.write("<a href='eit.html#eitis'>(εἴ τις), εἴτις</a>, ");
document.write("<a href='eit.html#eitoi'>εἴτοι</a>, ");
document.write("<a href='epan.html#epan'>ἐπάν</a>, ");
document.write("<a href='epei.html#epei'>ἐπεί</a>, ");
document.write("<a href='epei.html#epeidan'>ἐπειδάν</a>, ");
document.write("<a href='epei.html#epeidh'>ἐπειδή</a>, ");
document.write("<a href='epei.html#epeidhper'>ἐπειδήπερ</a>, ");
document.write("<a href='epei.html#epeiper'>ἐπείπερ</a>, ");
document.write("<a href='ew.html#ews'>ἕως</a>, ");
document.write("<a href='ga.html#gar'>γάρ</a>, ");
document.write("<a href='go.html#goun'>γοῦν</a>, ");
document.write("<a href='h.html#h1'>ἤ</a>, ");
document.write("<a href='hd.html#hdw'>ἥδω</a>, ");
document.write("<a href='hg.html#hgoun'>ἤγουν</a>, ");
document.write("<a href='hn.html#hnikaan'>(ἡνίκα ἄν)</a>, ");
document.write("<a href='ht.html#htoi'>ἤτοι</a>, ");
document.write("<a href='in.html#ina'>ἵνα</a>, ");
document.write("<a href='kag.html#kagw'>κἀγώ</a>, ");
document.write("<a href='kai.html#kai'>καί</a>, ");
document.write("<a href='kai.html#kaiekei'>καΐἐκεῖ</a>, ");
document.write("<a href='kai.html#kaiemos'>καϊἐμός</a>, ");
document.write("<a href='kai.html#kaiper'>καίπερ</a>, ");
document.write("<a href='kai.html#kaitaloipa'>(καὶ τὰ λοιπά)</a>, ");
document.write("<a href='kai.html#kaitoi'>καίτοι</a>, ");
document.write("<a href='kai.html#kaitoige'>καίτοιγε, (καίτοι γε)</a>, ");
document.write("<a href='kak.html#kakeiqen'>κἀκεῖθεν</a>, ");
document.write("<a href='kag.html#kame'>κἀμέ</a>, ");
document.write("<a href='kag.html#kamoi'>κἀμοί</a>, ");
document.write("<a href='kal.html#kallion'>κάλλιον</a>, ");
document.write("<a href='kam.html#kamou'>κἀμοῦ</a>, ");
document.write("<a href='kam.html#kan'>κἂν</a>, ");
document.write("<a href='kaq.html#kaqaper'>καθάπερ</a>, ");
document.write("<a href='kt.html#ktl'>κ.τ.λ.</a>, ");
document.write("<a href='ma.html#ma'>μά</a>, ");
document.write("<a href='men.html#mentoi'>μέντοι</a>, ");
document.write("<a href='men.html#mentoige'>μέντοιγε</a>, ");
document.write("<a href='mec.html#mecri'>μέχρι</a>, ");
document.write("<a href='mh.html#mhde'>μηδέ</a>, ");
document.write("<a href='mh.html#mhpou'>μήπου</a>, ");
document.write("<a href='mh.html#mhpws'>μήπως</a>, ");
document.write("<a href='mh.html#mhte'>μήτε</a>, ");
document.write("<a href='oi.html#oionei'>οἱονεί</a>, ");
document.write("<a href='om.html#omws'>ὅμως</a>, ");
document.write("<a href='op.html#opotan'>ὁπόταν</a>, ");
document.write("<a href='op.html#opws'>ὅπως</a>, ");
document.write("<a href='os.html#osakisan'>(ὁσάκις ἄν)</a>, ");
document.write("<a href='ot.html#otan'>ὅταν</a>, ");
document.write("<a href='ot.html#ote'>ὅτε</a>, ");
document.write("<a href='ot.html#otean'>ὅτε ἄν</a>, ");
document.write("<a href='ot.html#oti'>ὅτι</a>, ");
document.write("<a href='ou.html#oun'>οὖν</a>, ");
document.write("<a href='ou.html#oute'>οὔτε</a>, ");
document.write("<a href='plh.html#plhn'>πλήν</a>, ");
document.write("<a href='pri.html#prin'>πρίν</a>, ");
document.write("<a href='ta.html#tanun'>τανῦν</a>, ");
document.write("<a href='ta.html#tacion'>τάχιον</a>, ");
document.write("<a href='te.html#te'>τε</a>, ");
document.write("<a href='to.html#toinun'>τοίνυν</a>, ");
document.write("<a href='to.html#toiosde'>τοιόσδε</a>, ");
document.write("<a href='to.html#tounantion'>τοὐναντίον</a>, ");
document.write("<a href='to.html#tounoma'>τοὔνομα</a>, ");
document.write("<a href='ws.html#ws'>ὡς</a>,  ");
document.write("<a href='ws.html#wsan'>ὡσάν, (ὡς ἄν)</a>, ");
document.write("<a href='ws.html#wste'>ὥστε</a>, ");



document.write("<a href='ws.html#wste'>ὥστε</a> ");
document.write("</span></p>");