document.write("<div class='halfmoon'>");
document.write("<ul>");
document.write(" <li><span class='w'>Book I:</span> </li>");
document.write(" <li><a href='ps01.html'>1 - 42</a></li>");
document.write(" <li><span class='w'>Book II:</span> </li>");
document.write(" <li><a href='ps42.html'>42 - 72</a></li>");
document.write("</br>");
document.write (" <li><span class='w'>Book III:</span> </li>");
document.write (" <li><a href='ps73.html'>73 - 89</a></li>");
document.write("</ul>");
document.write("</div>");

document.write ("<div class='halfmoon'>");
document.write ("<ul>");
document.write (" <li><span class='w'>Book IV:</span> </li>");
document.write (" <li><a href='ps90.html'>90</a></li>");
document.write (" <li><a href='ps91.html'>91</a></li>");
document.write (" <li><a href='ps92.html'>92</a></li>");
document.write (" <li><a href='ps93.html'>93</a></li>");
document.write (" <li><a href='ps94.html'>94</a></li>");
document.write (" <li><a href='ps95.html'>95</a></li>");
document.write (" <li><a href='ps96.html'>96</a></li>");
document.write (" <li><a href='ps97.html'>97</a></li>");
document.write("</br>");
document.write (" <li><a href='ps98.html'>98</a></li>");
document.write (" <li><a href='ps99.html'>99</a></li>");
document.write (" <li><a href='ps100.html'>100</a></li>");
document.write (" <li><a href='ps101.html'>101</a></li>");
document.write (" <li><a href='ps102.html'>102</a></li>");
document.write (" <li><a href='ps103.html'>103</a></li>");
document.write (" <li><a href='ps104.html'>104</a></li>");
document.write (" <li><a href='ps105.html'>105</a></li>");
document.write("</br>");
document.write (" <li><a href='ps106.html'>106</a></li>");
document.write ("</ul>");
document.write ("</div>");
document.write ("<div class='halfmoon'>");
document.write ("<ul>");
document.write (" <li><span class='w'>Book V:</span> </li>");
document.write (" <li><a href='ps107.html'>107 - 150</a></li>");
document.write ("</ul>");
document.write ("</div>");
