document.write("<div class='halfmoon'>");
document.write("<ul>");
document.write(" <li><span class='w'>Book I:</span> </li>");
document.write(" <li><a href='ps01.html'>1 - 41</a></li>");
document.write(" <li><span class='w'>Book II:</span> </li>");
document.write(" <li><a href='ps42.html'>42 - 72</a></li>");
document.write("</ul>");
document.write("</div>");
document.write("<div class='halfmoon'>");
document.write("<ul>");
document.write (" <li><span class='w'>Book III:</span> </li>");
document.write (" <li><a href='ps73.html'>73 - 89</a></li>");
document.write (" <li><span class='w'>Book IV:</span> </li>");
document.write (" <li><a href='ps90.html'>90 - 106</a></li>");
document.write ("</ul>");
document.write ("</div>");

document.write ("<div class='halfmoon'>");
document.write ("<ul>");
document.write (" <li><span class='w'>Book V:</span> </li>");
document.write (" <li><a href='ps107.html'>107</a></li>");
document.write (" <li><a href='ps108.html'>108</a></li>");
document.write (" <li><a href='ps109.html'>109</a></li>");
document.write (" <li><a href='ps110.html'>110</a></li>");
document.write (" <li><a href='ps111.html'>111</a></li>");
document.write (" <li><a href='ps112.html'>112</a></li>");
document.write("</br>");
document.write (" <li><a href='ps113.html'>113</a></li>");
document.write (" <li><a href='ps114.html'>114</a></li>");
document.write (" <li><a href='ps115.html'>115</a></li>");
document.write (" <li><a href='ps116.html'>116</a></li>");
document.write (" <li><a href='ps117.html'>117</a></li>");
document.write (" <li><a href='ps118.html'>118</a></li>");
document.write (" <li><a href='ps119.html'>119</a></li>");
document.write("</br>");
document.write (" <li><a href='ps120.html'>120</a></li>");
document.write (" <li><a href='ps121.html'>121</a></li>");
document.write (" <li><a href='ps122.html'>122</a></li>");
document.write (" <li><a href='ps123.html'>123</a></li>");
document.write (" <li><a href='ps124.html'>124</a></li>");
document.write (" <li><a href='ps125.html'>125</a></li>");
document.write (" <li><a href='ps126.html'>126</a></li>");
document.write("</br>");
document.write (" <li><a href='ps127.html'>127</a></li>");
document.write (" <li><a href='ps128.html'>128</a></li>");
document.write (" <li><a href='ps129.html'>129</a></li>");
document.write (" <li><a href='ps130.html'>130</a></li>");
document.write (" <li><a href='ps131.html'>131</a></li>");
document.write (" <li><a href='ps132.html'>132</a></li>");
document.write (" <li><a href='ps133.html'>133</a></li>");
document.write("</br>");
document.write (" <li><a href='ps134.html'>134</a></li>");
document.write (" <li><a href='ps135.html'>135</a></li>");
document.write (" <li><a href='ps136.html'>136</a></li>");
document.write (" <li><a href='ps137.html'>137</a></li>");
document.write (" <li><a href='ps138.html'>138</a></li>");
document.write (" <li><a href='ps139.html'>139</a></li>");
document.write (" <li><a href='ps140.html'>140</a></li>");
document.write("</br>");
document.write (" <li><a href='ps141.html'>141</a></li>");
document.write (" <li><a href='ps142.html'>142</a></li>");
document.write (" <li><a href='ps143.html'>143</a></li>");
document.write (" <li><a href='ps144.html'>144</a></li>");
document.write (" <li><a href='ps145.html'>145</a></li>");
document.write (" <li><a href='ps146.html'>146</a></li>");
document.write (" <li><a href='ps147.html'>147</a></li>");
document.write("</br>");
document.write (" <li><a href='ps148.html'>148</a></li>");
document.write (" <li><a href='ps149.html'>149</a></li>");
document.write (" <li><a href='ps150.html'>150</a></li>");
// document.write (" <li><a href='ps151.html'>151</a></li>");
document.write ("</ul>");
document.write ("</div>");
