document.write("<div class='halfmoon'>");
document.write("<ul>");
document.write(" <li><span class='w'>Book I:</span> </li>");
document.write(" <li><a href='ps01.html'>1 - 41</a></li>");
document.write("</ul>");
document.write("</div>");
document.write("<div class='halfmoon'>");
document.write("<ul>");
document.write(" <li><span class='w'>Book II:</span> </li>");

document.write(" <li><a href='ps42.html'>42</a></li>");
document.write(" <li><a href='ps43.html'>43</a></li>");
document.write(" <li><a href='ps44.html'>44</a></li>");
document.write(" <li><a href='ps45.html'>45</a></li>");
document.write(" <li><a href='ps46.html'>46</a></li>");
document.write(" <li><a href='ps47.html'>47</a></li>");
document.write(" <li><a href='ps48.html'>48</a></li>");
document.write(" <li><a href='ps49.html'>49</a></li>");
document.write("</br>");
document.write (" <li><a href='ps50.html'>50</a></li>");
document.write (" <li><a href='ps51.html'>51</a></li>");
document.write (" <li><a href='ps52.html'>52</a></li>");
document.write (" <li><a href='ps53.html'>53</a></li>");
document.write (" <li><a href='ps54.html'>54</a></li>");
document.write (" <li><a href='ps55.html'>55</a></li>");
document.write (" <li><a href='ps56.html'>56</a></li>");
document.write (" <li><a href='ps57.html'>57</a></li>");
document.write (" <li><a href='ps58.html'>58</a></li>");
document.write (" <li><a href='ps59.html'>59</a></li>");
document.write("</br>");
document.write (" <li><a href='ps60.html'>60</a></li>");
document.write (" <li><a href='ps61.html'>61</a></li>");
document.write (" <li><a href='ps62.html'>62</a></li>");
document.write (" <li><a href='ps63.html'>63</a></li>");
document.write (" <li><a href='ps64.html'>64</a></li>");
document.write (" <li><a href='ps65.html'>65</a></li>");
document.write (" <li><a href='ps66.html'>66</a></li>");
document.write (" <li><a href='ps67.html'>67</a></li>");
document.write (" <li><a href='ps68.html'>68</a></li>");
document.write (" <li><a href='ps69.html'>69</a></li>");
document.write("</br>");
document.write (" <li><a href='ps70.html'>70</a></li>");
document.write (" <li><a href='ps71.html'>71</a></li>");
document.write (" <li><a href='ps72.html'>72</a></li>");
document.write ("</ul>");
document.write ("</div>");
document.write("<div class='halfmoon'>");
document.write("<ul>");
document.write (" <li><span class='w'>Book III:</span> </li>");
document.write (" <li><a href='ps73.html'>73 - 89</a></li>");

document.write (" <li><span class='w'>Book IV:</span> </li>");
document.write (" <li><a href='ps90.html'>90 - 106</a></li>");
document.write ("<br>");
document.write (" <li><span class='w'>Book V:</span> </li>");
document.write (" <li><a href='ps107.html'>107 - 150</a></li>");
document.write ("</ul>");
document.write ("</div>");
