document.write("<div class='halfmoon'>");
document.write("<ul>");
document.write(" <li><span class='w'>Book I:</span> </li>");
document.write(" <li><a href='ps01.html'>1 - 42</a></li>");
document.write(" <li><span class='w'>Book II:</span> </li>");
document.write(" <li><a href='ps42.html'>42 - 72</a></li>");
document.write("</ul>");
document.write("</div>");
document.write("<div class='halfmoon'>");
document.write("<ul>");
document.write ("</ul>");
document.write ("</div>");
document.write ("<div class='halfmoon'>");
document.write ("<ul>");
document.write (" <li><span class='w'>Book III:</span> </li>");
document.write (" <li><a href='ps73.html'>73</a></li>");
document.write (" <li><a href='ps74.html'>74</a></li>");
document.write (" <li><a href='ps75.html'>75</a></li>");
document.write (" <li><a href='ps76.html'>76</a></li>");
document.write (" <li><a href='ps77.html'>77</a></li>");
document.write (" <li><a href='ps78.html'>78</a></li>");
document.write (" <li><a href='ps79.html'>79</a></li>");
document.write (" <li><a href='ps80.html'>80</a></li>");
document.write("</br>");
document.write (" <li><a href='ps81.html'>81</a></li>");
document.write (" <li><a href='ps82.html'>82</a></li>");
document.write (" <li><a href='ps83.html'>83</a></li>");
document.write (" <li><a href='ps84.html'>84</a></li>");
document.write (" <li><a href='ps85.html'>85</a></li>");
document.write (" <li><a href='ps86.html'>86</a></li>");
document.write (" <li><a href='ps87.html'>87</a></li>");
document.write (" <li><a href='ps88.html'>88</a></li>");
document.write (" <li><a href='ps89.html'>89</a></li>");
document.write ("</ul>");
document.write ("</div>");
document.write ("<div class='halfmoon'>");
document.write ("<ul>");
document.write (" <li><span class='w'>Book IV:</span> </li>");
document.write (" <li><a href='ps90.html'>90 - 106</a></li>");
document.write (" <li><span class='w'>Book V:</span> </li>");
document.write (" <li><a href='ps107.html'>107 - 150</a></li>");
// document.write (" <li><a href='ps151.html'>151</a></li>");
document.write ("</ul>");
document.write ("</div>");
