document.write("<div class='halfmoon'>");
document.write("<ul>");
document.write(" <li><span class='w'>Book I:</span> </li>");
document.write(" <li><a href='ps01.html'>1</a></li>");
document.write(" <li><a href='ps02.html'>2</a></li>");
document.write(" <li><a href='ps03.html'>3</a></li>");
document.write(" <li><a href='ps04.html'>4</a></li>");
document.write(" <li><a href='ps05.html'>5</a></li>");
document.write(" <li><a href='ps06.html'>6</a></li>");
document.write(" <li><a href='ps07.html'>7</a></li>");
document.write(" <li><a href='ps08.html'>8</a></li>");
document.write(" <li><a href='ps09.html'>9</a></li>");
document.write(" <li><a href='ps10.html'>10</a></li>");
document.write(" <li><a href='ps11.html'>11</a></li>");
document.write(" <li><a href='ps12.html'>12</a></li>");
document.write("</br>");
document.write(" <li><a href='ps13.html'>13</a></li>");
document.write(" <li><a href='ps14.html'>14</a></li>");
document.write(" <li><a href='ps15.html'>15</a></li>");
document.write(" <li><a href='ps16.html'>16</a></li>");
document.write(" <li><a href='ps17.html'>17</a></li>");
document.write(" <li><a href='ps18.html'>18</a></li>");
document.write(" <li><a href='ps19.html'>19</a></li>");
document.write(" <li><a href='ps20.html'>20</a></li>");
document.write(" <li><a href='ps21.html'>21</a></li>");
document.write(" <li><a href='ps22.html'>22</a></li>");
document.write("</br>");
document.write(" <li><a href='ps23.html'>23</a></li>");
document.write(" <li><a href='ps24.html'>24</a></li>");
document.write(" <li><a href='ps25.html'>25</a></li>");
document.write(" <li><a href='ps26.html'>26</a></li>");
document.write(" <li><a href='ps27.html'>27</a></li>");
document.write(" <li><a href='ps28.html'>28</a></li>");
document.write(" <li><a href='ps29.html'>29</a></li>");
document.write(" <li><a href='ps30.html'>30</a></li>");
document.write(" <li><a href='ps31.html'>31</a></li>");
document.write(" <li><a href='ps32.html'>32</a></li>");
document.write("</br>");
document.write(" <li><a href='ps33.html'>33</a></li>");
document.write(" <li><a href='ps34.html'>34</a></li>");
document.write(" <li><a href='ps35.html'>35</a></li>");
document.write(" <li><a href='ps36.html'>36</a></li>");
document.write(" <li><a href='ps37.html'>37</a></li>");
document.write(" <li><a href='ps38.html'>38</a></li>");
document.write(" <li><a href='ps39.html'>39</a></li>");
document.write(" <li><a href='ps40.html'>40</a></li>");
document.write(" <li><a href='ps41.html'>41</a></li>");
document.write("</ul>");
document.write("</div>");
document.write("<div class='halfmoon'>");
document.write("<ul>");
document.write(" <li><span class='w'>Book II:</span> </li>");
document.write(" <li><a href='ps42.html'>42 - 72</a></li>");
document.write (" <li><span class='w'>Book III:</span> </li>");
document.write (" <li><a href='ps73.html'>73 - 89</a></li>");
document.write ("</ul>");
document.write ("</div>");
document.write ("<div class='halfmoon'>");
document.write ("<ul>");
document.write (" <li><span class='w'>Book IV:</span> </li>");
document.write (" <li><a href='ps90.html'>90 - 106</a></li>");
document.write (" <li><span class='w'>Book V:</span> </li>");
document.write (" <li><a href='ps107.html'>107 - 150</a></li>");
document.write ("</ul>");
document.write ("</div>");
