// primary menu
document.write("<div class='navbar'>");
	document.write("<div class='dropdown'>");
		document.write("<button class='dropbtn'>Home ");
			document.write("<i class='fa fa-caret-down'></i>");
		document.write("</button>");
		document.write("<div class='dropdown-content'>");
document.write("<a href='../trivia/trivia.html' title='Greek trivia'>Trivia</a>");
			document.write("<a href='../literature/books.html' title='Available books for sale'>Literature</a>");
			document.write("<a href='../help/help.html'>Help</a>");
			document.write("<a href='../about/about.html' title='contact information'>About</a>");
		document.write("</div>");
	document.write("</div> ");

	document.write("<div class='dropdown'>");
		document.write("<button class='dropbtn'>NT ");
			document.write("<i class='fa fa-caret-down'></i>");
		document.write("</button>");
		document.write("<div class='dropdown-content'>");
			document.write("<a href='../nt/mt01.html' title='New Testament'>NT (NAS)</a>");
			document.write("<a href='../nt-tr/mt01.html' title='New Testament'>NT (TexRec)</a>");
			document.write("<a href='../nt-poly/mt01.html' title='New Testament'>NT (parallel)</a>");
		document.write("</div>");
	document.write("</div> ");

	document.write("<div class='dropdown'>");
		document.write("<button class='dropbtn'>OT");
			document.write("<i class='fa fa-caret-down'></i>");
		document.write("</button>");
		document.write("<div class='dropdown-content'>");
			document.write("<a href='../lxx/genesis01.html' title='LXX'>LXX</a>");
			document.write("<a href='../polyglot/genesis01.html' title='polyglot'>OT Polyglot</a>");
		document.write("</div>");
	document.write("</div> ");

	document.write("<div class='dropdown'>");
		document.write("<button class='dropbtn'>Lexicon ");
			document.write("<i class='fa fa-caret-down'></i>");
		document.write("</button>");
		document.write("<div class='dropdown-content'>");
			document.write("<a href='../lexicon/a.html'>Greek to English</a>");
			document.write("<a href='../english/intro.html'>English to Greek</a>");
		document.write("</div>");
	document.write("</div> ");

				document.write("<a href='../apocrypha/baruch1.html'>Apocrypha</a>");
				document.write("<a href='../early/didache.html' title='Early Christian Documents'>Early Church</a>");
				document.write("<a href='../lessons/lesson01.html' title='How to learn Greek'>Tutorial</a>");
			document.write("</div>");
			document.write("<h1>KOINE GREEK LEXICON</h1>");
			document.write("<div class='yellowmoon'>");
				document.write("<ul>");
document.write("<li><a href='aa.html'>&#945;</a></li>");
document.write("<li><a href='ba.html'>&#946;</a></li>");
document.write("<li><a href='ga.html'>&#947;</a></li>");
document.write("<li><a href='da.html'>&#948;</a></li>");
document.write("<li><a href='ea.html'>&#949;</a></li>");
document.write("<li><a href='za.html'>&#950;</a></li>");
document.write("<li><a href='hg.html'>&#951;</a></li>");
document.write("<li><a href='qa.html'>&#952;</a></li>");
document.write("<li><a href='ia.html'>&#953;</a></li>");
document.write("<li><a href='ka.html'>&#954;</a></li>");
document.write("<li><a href='la.html'>&#955;</a></li>");
document.write("<li><a href='ma.html'>&#956;</a></li>");
document.write("<li><a href='na.html'>&#957;</a></li>");
document.write("<li><a href='xa.html'>&#958;</a></li>");
document.write("<li><a href='ob.html'>&#959;</a></li>");
				document.write("</ul>");
			document.write("</div>");
			document.write("<div class='yellowmoon'>");
				document.write("<ul>");
document.write("<li><a href='pa.html'>&#960;</a></li>");
document.write("<li><a href='ra.html'>&#961;</a></li>");
document.write("<li><a href='sa.html'>&#963;</a></li>");
document.write("<li><a href='ta.html'>&#964;</a></li>");
document.write("<li><a href='ud.html'>&#965;</a></li>");
document.write("<li><a href='fa.html'>&#966;</a></li>");
document.write("<li><a href='ca.html'>&#967;</a></li>");
document.write("<li><a href='ya.html'>&#968;</a></li>");
document.write("<li><a href='wb.html'>&#969;</a></li>");
document.write("<li><a href='../lexicon/a.html'>Lexicon</a></li>");
				document.write("</ul>");
			document.write("</div>");
